-- MySQL Script generated by MySQL Workbench
-- Sat Mar  7 15:23:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  `birthdate` DATE NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`winery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`winery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `postal_address` TEXT(512) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pdo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pdo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `postal_address` TEXT(512) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wine_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wine_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `description` TEXT(1024) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `winery_id` INT NOT NULL,
  `vintage` DATE NOT NULL,
  `pdo_id` INT NOT NULL,
  `wine_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wine_winery_idx` (`winery_id` ASC) VISIBLE,
  INDEX `fk_wine_pdo1_idx` (`pdo_id` ASC) VISIBLE,
  INDEX `fk_wine_wine_type1_idx` (`wine_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_wine_winery`
    FOREIGN KEY (`winery_id`)
    REFERENCES `mydb`.`winery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_pdo1`
    FOREIGN KEY (`pdo_id`)
    REFERENCES `mydb`.`pdo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_wine_type1`
    FOREIGN KEY (`wine_type_id`)
    REFERENCES `mydb`.`wine_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grape_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grape_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wine_grape_composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wine_grape_composition` (
  `grape_type_id` INT NOT NULL,
  `wine_id` INT NOT NULL,
  `percentage` TINYINT(100) UNSIGNED NOT NULL,
  INDEX `fk_wine_grape_composition_grape_type1_idx` (`grape_type_id` ASC) VISIBLE,
  INDEX `fk_wine_grape_composition_wine1_idx` (`wine_id` ASC) VISIBLE,
  CONSTRAINT `fk_wine_grape_composition_grape_type1`
    FOREIGN KEY (`grape_type_id`)
    REFERENCES `mydb`.`grape_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_grape_composition_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `mydb`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wine_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wine_list` (
  `user_id` INT NOT NULL,
  `wine_id` INT NOT NULL,
  `score` TINYINT(10) UNSIGNED NOT NULL,
  `modified_on` DATE NOT NULL,
  INDEX `fk_wine_list_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_wine_list_wine1_idx` (`wine_id` ASC) VISIBLE,
  CONSTRAINT `fk_wine_list_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_list_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `mydb`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`follower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`follower` (
  `user_id` INT NOT NULL,
  `to_follow_user_id` INT NOT NULL,
  `approved` TINYINT NOT NULL DEFAULT 0,
  `answered` TINYINT NOT NULL DEFAULT 0,
  `asked_on` DATE NOT NULL,
  INDEX `fk_follower_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_follower_user2_idx` (`to_follow_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_follower_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follower_user2`
    FOREIGN KEY (`to_follow_user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
