spring.application.name=winesocial
server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.url=jdbc:mariadb://server-domain:3306/wdb?useSSL=false&serverTimezone=UTC
